Make goto async
PrismarineJS/mineflayer-pathfinder pull request #107
Opened 2021-01-20 04:01 UTC by u9g

2021-01-20 05:00 UTC, u9g commented
might want to hold off on this, as it's probably a better idea to make a new gotoasync() function instead of just rewriting goto() as that would break existing projects

2021-01-20 08:02 UTC, rom1504 requested changes
Can you use the same technique we used in mineflayer ?
Ie make it async but use a callbackify function on top so it both returns a promise and take a callback.

2021-01-21 07:39 UTC, Karang requested changes

2021-01-21 07:39 UTC, Karang commented on lib/goto.js
> +// }
If this function is not needed, remove it, don't comment.

2021-01-21 07:39 UTC, Karang commented on lib/goto.js
> +    }
This callback does nothing. It should reject in case the status is noPath.

2021-01-21 07:39 UTC, Karang commented on lib/goto.js
> +    }
if the goal is changed newGoal !== goal, it should reject the promise

2021-01-21 22:32 UTC, merged