Fixed placeBlock example
PrismarineJS/mineflayer-pathfinder pull request #196
Opened 2021-09-06 12:54 UTC by IceTank

2021-09-06 12:55 UTC, IceTank commented
The command 'come' was not working.

2021-09-26 13:51 UTC, rom1504 commented
can you check this @Karang or @u9g ?

2021-09-26 18:56 UTC, u9g requested changes
just one small thing, otherwise looks good

2021-09-26 18:56 UTC, u9g commented on examples/placeBlock.js
> +    const target = bot.players[username].entity
if you just dont make this change, the you don't need to make the change below

2021-09-26 19:00 UTC, Karang commented
This is already merged ?

2021-09-26 19:05 UTC, u9g commented
> This is already merged ?

oh I guess it was

2021-09-26 19:05 UTC, closed without merging