check if a goal is still valid before checking if the goal has changed
PrismarineJS/mineflayer-pathfinder pull request #206
Opened 2021-09-29 01:55 UTC by u9g

2022-01-09 17:55 UTC, IceTank commented
I don't think every goal has to implement the function `isValid()` it should work if only the methods that override the default method should implement a `isValid()` method.

2022-02-13 18:01 UTC, rom1504 commented
I will close this next week if no feedback given

2022-02-13 20:28 UTC, IceTank commented
I think the pr is fine the isValid() method is removed from every goal. It should be fine if isValid just returns true by default in the Parent Goal class. Only dynamic goals where the goal could get invalid should need the isValid method.

@u9g Can you refactor it? It should be ready to merge then.

2022-02-13 21:39 UTC, rom1504 commented
If you want, you can directly edit this @IceTank , you have rights to do it

2022-02-13 21:44 UTC, u9g commented
> I think the pr is fine the isValid() method is removed from every goal. It should be fine if isValid just returns true by default in the Parent Goal class. Only dynamic goals where the goal could get invalid should need the isValid method.
> 
> @u9g Can you refactor it? It should be ready to merge then.

Done.

2022-02-14 00:25 UTC, IceTank requested changes

2022-02-14 00:25 UTC, IceTank commented on lib/goals.js
> +    return false
This should be `return true`

2022-02-14 00:25 UTC, IceTank commented on lib/goals.js
> +    return false
Same here

2022-02-14 18:49 UTC, u9g commented on lib/goals.js
> +    return false
done!

2022-02-14 19:38 UTC, IceTank approved these changes

2022-02-14 19:39 UTC, IceTank commented
@Karang anything to add? Or can we merge this?

2022-02-20 11:11 UTC, merged