Set every non diggable block automatically from mcdata
PrismarineJS/mineflayer-pathfinder pull request #72
Opened 2020-11-19 11:03 UTC by MrAlexEsisteGia

This should theoretically work but I haven't tested it yet in action

2020-11-19 16:10 UTC, NotSugden requested changes
needs spacing improvements, also might it be better to have a setting (boolean) to go after unbreakable blocks rather than add them all to this `Set` of blocks

2020-11-19 16:11 UTC, NotSugden commented
the branch you made for this PR needs rebasing, as it is based off the same branch as your previous PR #55

2020-12-03 04:56 UTC, MrAlexEsisteGia commented
> 
> 
> needs spacing improvements, also might it be better to have a setting (boolean) to go after unbreakable blocks rather than add them all to this `Set` of blocks

to me, it seems a bit excessive, it was already marking a few unbreakable blocks manually

2020-12-03 05:06 UTC, TheDudeFromCI requested changes
Since we have chests in this list by default, it might be a good idea to add all other inventory holding blocks as well.

2020-12-03 05:13 UTC, MrAlexEsisteGia commented
> 
> 
> Since we have chests in this list by default, it might be a good idea to add all other inventory holding blocks as well.

there is no easy way to add them automatically so, wouldn't a bool like "dontMineImportantBlocks" be better?
with also other blocks in it (like diamond blocks - doors - ladders - spawners - ecc...)

2020-12-03 06:27 UTC, TheDudeFromCI commented
They would have to be added manually like chests are.

2020-12-05 16:15 UTC, MrAlexEsisteGia commented
@Karang do I need to change anything or is this good

2020-12-05 16:23 UTC, rom1504 commented
small note here: if this is merged, it should be merged with "squash and merge" button to avoid having so many commits

2020-12-05 16:27 UTC, Karang commented
> @Karang do I need to change anything or is this good

The PR seems fine, can you rebase on master and squash your commit ? For a 4 line change, 20 commits is a bit too much ;)

2020-12-05 16:45 UTC, rom1504 commented
That was my point about the GitHub squash and merge button, it does the squashing

2020-12-05 16:49 UTC, Karang commented
> That was my point about the GitHub squash and merge button, it does the squashing

If I squash it myself it seems like it will change the author. I'd prefer if the author squash it before I merge.

2020-12-05 17:06 UTC, rom1504 commented
https://github.com/PrismarineJS/mineflayer/commits/master GitHub handles it properly. All these commits with a PR id in parentheses are merged with "squash and merge"
It indicates the original author in addition to having a single clean commit
I think it works pretty well

2020-12-05 17:14 UTC, merged

2020-12-05 17:15 UTC, Karang commented
@rom1504  yeah ok it works, it wasn't clear from the gui